import { Component, EventEmitter, Inject, Input, OnChanges, OnDestroy, Output, PLATFORM_ID, SimpleChanges } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import * as THREE from 'three';
import { Project } from '../../models/project.model';
import { Scene3dCanvasComponent } from './scene-3d-canvas.component';
import { ThreeSceneService } from '../services/three-scene.service';
import { InteractionManagerService } from '../services/interaction-manager.service';

@Component({
  selector: 'app-project-visualizer', standalone: true, imports: [Scene3dCanvasComponent],
  template: `<section class="project-gallery" aria-label="Interactive project gallery"><app-3d-scene-canvas (sceneReady)="onSceneReady($event)"></app-3d-scene-canvas><div class="hud"><p>PROJECT ARCHIVE / 3D</p><h2>{{ selectedProject?.title || 'Select a project' }}</h2><span>{{ selectedProject?.problem || 'Explore the work orbiting the gallery.' }}</span><div class="techs">@for (tech of selectedProject?.technologies?.slice(0, 4) || []; track tech) { <i>{{ tech }}</i> }</div></div><div class="rail">@for (project of projects.slice(0, 8); track project.id || project.title; let i = $index) { <button [class.active]="selectedProject?.id === project.id" (click)="select(project)"><b>0{{i + 1}}</b>{{project.title}}</button> }</div><small>CLICK A FLOATING PROJECT OR SELECT ONE BELOW</small></section>`,
  styles: [`:host{display:block}.project-gallery{height:min(650px,72vh);min-height:520px;position:relative;overflow:hidden;border:1px solid #6979e066;border-radius:1.75rem;background:radial-gradient(circle at 50% 48%,#182557 0,#090d20 38%,#03050d 100%);box-shadow:0 24px 80px #0008,inset 0 0 90px #6366f11a;isolation:isolate}.hud{position:absolute;z-index:2;top:clamp(1.5rem,5vw,4rem);left:clamp(1.5rem,6vw,5.5rem);width:min(22rem,43%);pointer-events:none}.hud p,small{color:#8ea2ff;font:700 .65rem/1 ui-monospace,monospace;letter-spacing:.18em}.hud h2{margin:.7rem 0;font-size:clamp(1.7rem,3.7vw,3.4rem);line-height:.98;font-weight:750}.hud span{color:#b7c0dc;font-size:.92rem;line-height:1.6}.techs{display:flex;flex-wrap:wrap;gap:.4rem;margin-top:1rem}.techs i{padding:.3rem .5rem;border:1px solid #7184f04d;border-radius:999px;color:#d5dcff;background:#0c123f91;font-size:.68rem;font-style:normal}.rail{position:absolute;z-index:2;left:1.25rem;right:1.25rem;bottom:1.25rem;display:flex;overflow:auto;gap:.45rem;scrollbar-width:none}.rail button{flex:0 0 auto;padding:.65rem .8rem;color:#bbc5ed;border:1px solid #42518170;border-radius:.65rem;background:#080d22ba;backdrop-filter:blur(10px);font-size:.72rem;text-align:left;transition:.25s}.rail button b{margin-right:.45rem;color:#7587ff;font:.62rem ui-monospace,monospace}.rail button:hover,.rail button.active{color:#fff;border-color:#8b95ff;background:#313b92c9;transform:translateY(-3px)}small{position:absolute;z-index:2;right:1.4rem;bottom:5rem;color:#a8b4df;font-size:.55rem}@media(max-width:700px){.project-gallery{min-height:530px;height:68vh}.hud{width:calc(100% - 3rem);top:1.5rem}small{display:none}}`]
})
export class ProjectVisualizerComponent implements OnChanges, OnDestroy {
  @Input() projects: Project[] = []; @Input() selectedProject: Project | null = null; @Output() projectSelected = new EventEmitter<Project>();
  private sceneService: ThreeSceneService | null = null; private interactions: InteractionManagerService | null = null; private gallery = new THREE.Group(); private meshes = new Map<string, THREE.Group>(); private stop: (() => void) | null = null; private textureLoader = new THREE.TextureLoader(); private magnet = new THREE.Vector3(); private magnetActive = false; private canvas: HTMLCanvasElement | null = null;
  constructor(@Inject(PLATFORM_ID) private platformId: object) {}
  ngOnChanges(changes: SimpleChanges): void { if (changes['projects'] && this.sceneService) this.build(); if (changes['selectedProject'] && this.sceneService) this.focus(); }
  onSceneReady(canvas: Scene3dCanvasComponent): void { if (!isPlatformBrowser(this.platformId)) return; this.sceneService=canvas.getSceneService(); this.interactions=canvas.getInteractionManager(); this.canvas=canvas.getCanvas(); this.canvas.addEventListener('pointermove',this.onPointerMove); this.canvas.addEventListener('pointerleave',this.onPointerLeave); const scene=this.sceneService.getScene(); scene.background=new THREE.Color(0x050716); this.sceneService.getCamera().position.set(0,1.1,13); this.sceneService.getCamera().lookAt(0,0,0); this.build(); }
  select(project: Project): void { this.projectSelected.emit(project); }
  private build(): void { const scene=this.sceneService?.getScene(); if(!scene)return; scene.remove(this.gallery); this.stop?.(); this.gallery=new THREE.Group(); this.meshes.clear(); scene.add(this.gallery); this.environment(); this.projects.slice(0,8).forEach((p,i)=>this.add(p,i)); this.focus(); this.stop=this.sceneService?.onUpdate(d=>{this.gallery.rotation.y+=d*.032;const balls=[...this.meshes.values()];const localCursor=this.gallery.worldToLocal(this.magnet.clone());balls.forEach((ball,index)=>{const velocity=ball.userData['velocity'] as THREE.Vector3;const force=new THREE.Vector3();balls.forEach((other,otherIndex)=>{if(index===otherIndex)return;const delta=other.position.clone().sub(ball.position);const distance=Math.max(delta.length(),.01);const desiredDistance=2.65;force.addScaledVector(delta.normalize(),(distance-desiredDistance)*.38);});if(this.magnetActive){const away=ball.position.clone().sub(localCursor);const distance=Math.max(away.length(),.01);if(distance<4.8)force.addScaledVector(away.normalize(),(1-distance/4.8)*15);}
        velocity.multiplyScalar(.91).addScaledVector(force,d);ball.position.addScaledVector(velocity,d);ball.rotation.y+=d*.12;const n=[...this.meshes.keys()][index]===this.selectedKey()?1.25:1;ball.scale.lerp(new THREE.Vector3(n,n,n),d*5);});})??null; }
  private environment(): void { const floor=new THREE.GridHelper(22,28,0x5367db,0x17224a);floor.position.y=-3.15;const mat=floor.material as THREE.Material;mat.transparent=true;mat.opacity=.45;this.gallery.add(floor);const light=new THREE.PointLight(0x6d7cff,80,16);light.position.set(0,2,2);this.gallery.add(light,new THREE.AmbientLight(0x7488ff,1.4)); }
  private add(project: Project,index:number): void { const angle=index/Math.max(this.projects.slice(0,8).length,1)*Math.PI*2;const group=new THREE.Group();group.position.set(Math.cos(angle)*4.5,Math.sin(index*1.8)*.55,Math.sin(angle)*2.2-.5);group.userData['velocity']=new THREE.Vector3();group.rotation.y=-angle;const color=[0x7c6cff,0x20c8dc,0xff7a98,0x43d996][index%4];this.projectOrb(group,project,color);this.meshes.set(this.key(project),group);group.traverse(o=>{if(o instanceof THREE.Mesh){this.interactions?.onClick(o,()=>this.select(project));this.interactions?.onHover(o,()=>document.body.style.cursor='pointer');}});this.gallery.add(group); }
  private projectOrb(group: THREE.Group, project: Project, color: number): void { const material=new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.12,metalness:.2,roughness:.48});const orb=new THREE.Mesh(new THREE.SphereGeometry(1.1,48,32),material);group.add(orb);if(project.image){this.textureLoader.load(project.image,(texture)=>{texture.colorSpace=THREE.SRGBColorSpace;material.map=texture;material.color.set(0xffffff);material.needsUpdate=true;},undefined,()=>undefined);}}
  private key(project: Project): string { return project.id || project.title; }
  private selectedKey(): string { return this.selectedProject ? this.key(this.selectedProject) : ''; }
  private onPointerMove = (event: PointerEvent): void => { if(!this.canvas)return;const rect=this.canvas.getBoundingClientRect();this.magnet.set(((event.clientX-rect.left)/rect.width-.5)*10,-((event.clientY-rect.top)/rect.height-.5)*6,1);this.magnetActive=true; };
  private onPointerLeave = (): void => { this.magnetActive=false; };
  private focus(){if(!this.selectedProject&&this.projects.length)this.select(this.projects[0]);} ngOnDestroy(){this.stop?.();this.canvas?.removeEventListener('pointermove',this.onPointerMove);this.canvas?.removeEventListener('pointerleave',this.onPointerLeave);}
}
